/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Herencia.Equipo;
import java.util.ArrayList;

/**
 *
 * @author daw-A
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        vEquipos = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelForm = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jTextFieldUbi = new javax.swing.JTextField();
        jTextFieldcoste = new javax.swing.JTextField();
        jCheckBoxProtegido = new javax.swing.JCheckBox();
        jButtonAñadir = new javax.swing.JButton();
        jButtonVerEquipos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaEquipos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelForm.setText("Datos equipo nuevo");

        jTextFieldCod.setText("Codigo de equipo");
        jTextFieldCod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCodFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCodFocusLost(evt);
            }
        });
        jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodActionPerformed(evt);
            }
        });

        jTextFieldUbi.setText("Ubicacion");
        jTextFieldUbi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUbiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUbiFocusLost(evt);
            }
        });
        jTextFieldUbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUbiActionPerformed(evt);
            }
        });

        jTextFieldcoste.setText("Coste");
        jTextFieldcoste.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldcosteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldcosteFocusLost(evt);
            }
        });

        jCheckBoxProtegido.setText("Protegido");

        jButtonAñadir.setText("Añadir");
        jButtonAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAñadirMouseClicked(evt);
            }
        });

        jButtonVerEquipos.setText("Ver Equipos");
        jButtonVerEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVerEquiposMouseClicked(evt);
            }
        });

        jTextAreaEquipos.setEditable(false);
        jTextAreaEquipos.setColumns(20);
        jTextAreaEquipos.setRows(5);
        jScrollPane1.setViewportView(jTextAreaEquipos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBoxProtegido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldcoste)
                    .addComponent(jTextFieldUbi)
                    .addComponent(jLabelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCod)
                    .addComponent(jButtonAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonVerEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelForm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonVerEquipos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUbi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldcoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxProtegido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAñadir)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodActionPerformed

    private void jTextFieldUbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUbiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUbiActionPerformed

    private void jButtonAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAñadirMouseClicked
        
        String codigo;
        String ubicacion;
        double coste;
        boolean protegido;
        codigo = jTextFieldCod.getText();
        ubicacion = jTextFieldUbi.getText();
        coste = Double.valueOf(jTextFieldcoste.getText());
        protegido = jCheckBoxProtegido.isSelected();
        
        Equipo e = new Equipo(codigo, ubicacion, coste, protegido);
        vEquipos.add(e);
        
        
    }//GEN-LAST:event_jButtonAñadirMouseClicked

    private void jButtonVerEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVerEquiposMouseClicked
        
        String texto="";
        
        for (Equipo e : vEquipos) {
        texto += e.toString() + "\n" ;
        }
        
        jTextAreaEquipos.setText(texto);
        
    }//GEN-LAST:event_jButtonVerEquiposMouseClicked

    private void jTextFieldCodFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCodFocusLost
        
        jTextFieldCod.setText("Codigos");
        
    }//GEN-LAST:event_jTextFieldCodFocusLost

    private void jTextFieldCodFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCodFocusGained
        
        jTextFieldCod.setText("");
        
    }//GEN-LAST:event_jTextFieldCodFocusGained

    private void jTextFieldUbiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUbiFocusGained

        jTextFieldUbi.setText("");

    }//GEN-LAST:event_jTextFieldUbiFocusGained

    private void jTextFieldcosteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldcosteFocusGained

        jTextFieldcoste.setText("");
        
    }//GEN-LAST:event_jTextFieldcosteFocusGained

    private void jTextFieldUbiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUbiFocusLost
         
       jTextFieldUbi.setText("ubicacion");
       
    }//GEN-LAST:event_jTextFieldUbiFocusLost

    private void jTextFieldcosteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldcosteFocusLost

        jTextFieldcoste.setText("coste");

    }//GEN-LAST:event_jTextFieldcosteFocusLost

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    private ArrayList<Equipo> vEquipos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonVerEquipos;
    private javax.swing.JCheckBox jCheckBoxProtegido;
    private javax.swing.JLabel jLabelForm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaEquipos;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldUbi;
    private javax.swing.JTextField jTextFieldcoste;
    // End of variables declaration//GEN-END:variables
}
